language: go

go:
  - '1.12'

dist: xenial

env:
  global:
    - GOLANG_LINT_VERSION=v1.16.0
    - GO111MODULE=on

addons:
  apt:
    packages:
      - curl
      - bash

before_script:
  - wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANG_LINT_VERSION}

script:
  - golangci-lint run ./... || exit 1
  - curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux