language: go

go:
  - '1.14'

dist: bionic

addons:
  apt:
    packages:
      - curl
      - bash
      - wget

before_script:
  - wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - golangci-lint run ./... || exit 1